---
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "ğŸ“¦ Dependency updates"
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "ğŸš€ New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "âš ï¸ Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "ğŸ Bug fixes"
      regexp: '^.*?(fix|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "ğŸ“š Documentation updates"
      regexp: ^.*?docs?(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "ğŸ—ï¸ Build process updates"
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "ğŸ§° Other work"
      order: 9999
